### ISSUE TITLE
MVP widget Internal feedback collection

### ISSUE THREAD

**Issue by kjgarza** [datacite/spitz#19]
Issue to correct internal feedback

The widget can be seen in:

https://support.datacite.org/docs/displaying-usage-and-citations-in-your-repository

**Comment by mfenner** [comment]
Feedback regarding the widget MVP:

1. The medium size widget is too big (currently about 100 x 70 px for the icons).
1. The medium size widget should have labels (citations, views, downloads) to make clear what the numbers indicate.
1. The size of the count in the medium widget should be larger relative to the icon.
1. The medium size widget should show the DOI ("Metrics for DOI...") on hover, similar to the small widget.
1. The small widget is too small (font size 8px). The font-size should be the same as a typical web page font size (e.g. 14px as on the support page).
1. Align colors in small widget with medium size widget (blue, greyish if zero count).
1. The small widget should be clickable, going to the DataCite Search page.
1. (beyond the MVP) look for (or design) clear icons for citations, views and downloads.

**Comment by richardhallett** [comment]
As an MVP it looks good to me in general.

My only thought would be the contrast of the text and the background colour on the small widget, it's not strong enough and makes it harder to read. I think I saw an a mockup with grey background with black text, which was clearer.
This might be improved slightly by increasing the font size.

As for sizes, perhaps the "medium" is a little larger than I'd expect medium to be, but if you renamed it "big" then it'd be fine.

**Comment by kjgarza** [comment]
for context, this is how the small widget looks like when used in Fabrica 

![image](https://user-images.githubusercontent.com/1092861/72131918-ed192c80-337d-11ea-8698-607fa622c824.png)

**Comment by MaryHirsch** [comment]
all four versions look OK to me although I agree that the version on slide 3 does look quite big. Could the blue on slide 3 and 4 be DataCite blue?

I think it's really important to get feedback from the users themselves.

and it would be nice to have a designer work on this to make sure the look and feel is consist with other DataCite materials.
