### ISSUE TITLE
graphql failing

### ISSUE THREAD

**Issue by adam-earthscope** [datacite/spitz#20]
I'm seeing 400 errors in both my local copy and the live demo, it's a graphql 400 error in an http 200 response:

```
{
  "errors": [
    {
      "message": "400: Bad Request",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "response": {
          "url": "https://api.datacite.org/client-api/graphql",
          "status": 400,
          "statusText": "Bad Request",
          "body": {
            "errors": [
              {
                "status": "400",
                "title": "undefined method `metadata' for QueryType:Class"
              }
            ]
          }
        }
      }
    }
  ],
  "data": null,
  "extensions": {
    "tracing": {
      "version": 1,
      "startTime": "2020-01-23T22:50:06.252Z",
      "endTime": "2020-01-23T22:50:07.154Z",
      "duration": 901837883,
      "execution": {
        "resolvers": []
      }
    }
  }
}
```

**Comment by kjgarza** [comment]
The problem with the GRaphql API is related to the `migration` issues we have in the API at the moment. The erros just started when the merge happened. And we did manage t ocapture some of the errors in sentry before it shut-off. See

https://sentry.io/organizations/datacite/issues/1466532344/?project=1410849&referrer=github_integration


```

result = LupoSchema.execute(query, variables: variables, context: context, operation_name: operation_name)

```
The errors seem at the executiong level.

I think we can discard teh grpahql query and types code right off the bat.

Another indication that this is related to the migration is to pull the last couple containers. These graphql erros just appear with the new containers


Last container without the Migrations
  >docker pull datacite/lupo:feature_metric_from_rest

First container with the migration
 > docker pull datacite/lupo:2.9.32

**Comment by mfenner** [comment]
Should be fixed via https://github.com/datacite/lupo/issues/400, but needs further testing.

**Comment by kjgarza** [comment]
this has been resolved errors are not appearing anymore. see demo in  https://support.datacite.org/docs/displaying-usage-and-citations-in-your-repository
